### ISSUE TITLE
Diagnostic and actions handlers are missing

### ISSUE THREAD

**Issue by lucax88x** [ojroques/nvim-lspfuzzy#5] opened 2020-12-14 15:39 UTC
Do you plan to support those handlers in the near future or are they out of scope?

**Comment by lucax88x** [comment] 2020-12-14 16:04
I am trying to do it myself, but I'm pretty newb with plugins in general, how can I source my luafile and overwrite handlers to test it?

**Comment by ojroques** [comment] 2020-12-14 18:02
The issue is that Neovim LSP does have a function to retrieve all diagnostics (`vim.lsp.diagnostic.get()`) but we cannot redefine the handler for that function. This is because that handler is used to display the warnings/erros next to the code so we don't want to mess with that.

So this means we have to create our own command which would call `vim.lsp.diagnostic.get()` and process the results. It shouldn't be complicated, I'll do it this week or the next.

About code_action I don't really see the point of using FZF in that case. There is no location to jump to, there is just a list from which to select an action. It's quicker to type `2` to select action 2 than to use FZF I'd say. So it's not a priority but maybe I'll add a command after the one for the diagnostics.

**Comment by lucax88x** [comment] 2020-12-14 22:25
Regarding diagnostic, Yeah, I think we could be fine by just providing a EX command that we can use in our remaps instead of using handlers.
Regarding actions, well, to me it happens to have also 10 actions to select from, and FZF can be helpful to filter quickly, and in general to have an unique "popup" system.

**Comment by ojroques** [comment] 2020-12-14 22:34
I'm working on both right now in branch `dev` you can try it out.

Diagnostics works fine, I've added a `:LspDiagnostics` command.

I haven't tested code actions yet because my LSP servers don't support them. Can you suggest me a LSP server which have some code actions I can try?

**Comment by lucax88x** [comment] 2020-12-14 22:58
TSServer has a lot of actions.

Tomorrow morning I'll try your branch.

**Comment by lucax88x** [comment] 2020-12-15 09:44
Almost perfect.

One side note, if there are no actions, I would print a message.

**Comment by ojroques** [comment] 2020-12-15 09:56
I've merged dev into main, now the plugin supports diagnostics and code actions.

**Closed by ojroques** 2020-12-15 09:56 UTC
